export const coffeesDB = {
  1: {
    titulo: "Expresso Tradicional",
    descricao: "O tradicional café feito com água quente e grãos moídos",
    valor: 9.9,
    img: "../src/assets/expresso.svg",
    tags: ["tradicional"],
    quantidade: 0,
  },
  2: {
    titulo: "Expresso Americano",
    descricao: "Expresso diluído, menos intenso que o tradicional",
    valor: 9.9,
    img: "../src/assets/americano.svg",
    tags: ["tradicional"],
    quantidade: 0,
  },
  3: {
    titulo: "Expresso Cremoso",
    descricao: "Café expresso tradicional com espuma cremosa",
    valor: 9.9,
    img: "../src/assets/expresso_cremoso.svg",
    tags: ["tradicional"],
    quantidade: 0,
  },
  4: {
    titulo: "Expresso Gelado",
    descricao: "Bebida preparada com café expresso e cubos de gelo",
    valor: 9.9,
    img: "../src/assets/cafe_gelado.svg",
    tags: ["tradicional", "gelado"],
    quantidade: 0,
  },
  5: {
    titulo: "Café com Leite",
    descricao: "Meio a meio de expresso tradicional com leite vaporizado",
    valor: 9.9,
    img: "../src/assets/cafe_com_leite.svg",
    tags: ["tradicional", "com leite"],
    quantidade: 0,
  },
  6: {
    titulo: "Latte",
    descricao:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    valor: 9.9,
    img: "../src/assets/latte.svg",
    tags: ["tradicional", "com leite"],
    quantidade: 0,
  },
  7: {
    titulo: "Capuccino",
    descricao:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    valor: 9.9,
    img: "../src/assets/capuccino.svg",
    tags: ["tradicional", "com leite"],
    quantidade: 0,
  },
  8: {
    titulo: "Macchiato",
    descricao: "Café expresso misturado com um pouco de leite quente e espuma",
    valor: 9.9,
    img: "../src/assets/macchiato.svg",
    tags: ["tradicional", "com leite"],
    quantidade: 0,
  },
  9: {
    titulo: "Chocolate Quente",
    descricao: "Bebida feita com chocolate dissolvido no leite quente e café",
    valor: 9.9,
    img: "../src/assets/chocolate_quente.svg",
    tags: ["especial", "com leite"],
    quantidade: 0,
  },
  10: {
    titulo: "Cubano",
    descricao:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    valor: 9.9,
    img: "../src/assets/cubano.svg",
    tags: ["especial", "alcoólico", "gelado"],
    quantidade: 0,
  },
  11: {
    titulo: "Havaiano",
    descricao: "Bebida adocicada preparada com café e leite de coco",
    valor: 9.9,
    img: "../src/assets/havaiano.svg",
    tags: ["especial"],
    quantidade: 0,
  },
};
